### PR TITLE
Konacha 3.0 compatibility

### PR DESCRIPTION
**Pull request by alexgb**
Rewrote most of the guard plugin to tie directly into Konacha::Server and added middleware into the stack to prevent the cacheing issues we were seeing. The new plugin is Konacha 3 compatible and tested against Rails 3.1, 3.2 and 4.0.

### CODE REVIEW

**Comment by alexgb** [comment]
@matthijsgroen Let me know if you'll have a chance to review in the next couple days. If not, I'll release and address issues as they come up.

**Comment by matthijsgroen** [comment]
I totally missed your message :-(

I'll start field testing right away :-)

**Comment by matthijsgroen** [comment]
It looks good, so far I found that the :all_on_start => false option is not respected

**Comment by alexgb** [comment]
Cool, thanks for your help. I'll look into that one.

**Pull request merged**
