### PR TITLE
Prevent caching results

### PR DESCRIPTION
**Pull request by matthijsgroen**
Reset Capybara session before each run to clear cookies (Cucumber::Rails does this aswell)

and add a unique identifier to the url to prevent cached results

Had to add Timecop as development dependency to guarantee uniqueness

### CODE REVIEW

**Comment by alexgb** [comment]
I was thinking this might be a good idea. Thanks!

**Comment by matthijsgroen** [comment]
No problem. I wanted to make sure this would help so was field-testing this for a few days to make sure it would solve the problem

**Comment by romanenko** [comment]
Strange, but from time to time my specs appears to be cached and only typing `reload konacha` helps. Why is it happening? To be honest, I don't really know how to reproduce the bug: it just happens from time to time.

**Comment by alexgb** [comment]
My guess is that there's some kind of caching happening in Capybara or its driver. @romanenko are you using the `:webkit` or `:poltergeist` driver?.

**Comment by romanenko** [comment]
@alexgb I use `:poltergeist`.

**Comment by matthijsgroen** [comment]
I have the same effect myself and an searching for a solution for months without success. We use the `:webkit` driver. Your discovery may indicate it is an issue within Capybara itself.

**Comment by romanenko** [comment]
Caching results still persists even when I use `:webkit` driver. 

For example, I start guard, and make changes in specs to fail them, but running succeeds. I type `reload konacha` in guard console — they are still green. Only when I type `exit` in guard console, then start it again — they fail.

**Comment by alexgb** [comment]
I have a fix for the caching issue and compatibility issues with Konacha 3.0 that I hope to get up this weekend. Stay tuned.

**Comment by matthijsgroen** [comment]
\o/

**Pull request merged**
