### PR TITLE
Fixed compatibility issues with guard 2 and converted specs to use rspec 3 conventions

### PR DESCRIPTION
**Pull request by lbeder**

### CODE REVIEW

**Comment by lbeder** [comment]
Obviously, supporting older rails versions and staying compatible with guard 2 is problematic.

**Comment by hauleth** [comment]
:+1:

**Comment by hugocorbucci** [comment]
Looks like most of the errors are rbx gem install issues. Not due to the changes here.
Any chance we can merge this in?

**Comment by romanbsd** [comment]
:+1:

**Comment by kamui** [comment]
Maybe just fork it and release it as new gem? The author seems to have abandoned this gem.

**Comment by lbeder** [comment]
Sure. I'll take care of it.

**Comment by lbeder** [comment]
#

**Comment by kamui** [comment]
You move swiftly :+1:

**Comment by lbeder** [comment]
Here you go: https://rubygems.org/gems/guard-konacha-rails

**Comment by lbeder** [comment]
Here you go: https://rubygems.org/gems/guard-konacha-rails.

**Pull request closed without merging**
